<?php

/**
 * ActeurTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ActeurTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ActeurTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Acteur');
    }
}