<?php

/**
 * CategorieFilmTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CategorieFilmTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CategorieFilmTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CategorieFilm');
    }
}