<?php

/**
 * ListeCategoriesFilmTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ListeCategoriesFilmTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ListeCategoriesFilmTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ListeCategoriesFilm');
    }
}